"""LLM integration wrapper for predictive maintenance reporting.

Phase 5: Multi-Model Architecture (Dynamic Routing)

This script simulates a real-time anomaly event by sampling one Fault window
from the batch feature table, dynamically routes the event to the correct
IsolationForest model based on motor load (HP), and (if anomalous) generates a
Vietnamese maintenance report using Google Gemini.

Prerequisites:
- features_multiload.csv (generated by pipeline_multimodel.py)
- iso_forest_load_{load_hp}HP.pkl models (generated by pipeline_multimodel.py)
- Environment variable: GEMINI_API_KEY

Run:
    python llm_integration.py
"""

from __future__ import annotations

import os

import joblib
import pandas as pd
from dotenv import load_dotenv
from google import genai


FEATURE_COLUMNS: list[str] = ["RMS", "Variance", "Kurtosis", "Peak_to_Peak"]


def simulate_realtime_data(csv_path: str) -> dict[str, float]:
    """Simulate real-time incoming data by sampling one Fault row.

    Phase 5 input is a multi-load feature table. We:
    - Read `features_multiload.csv`
    - Filter anomalous rows (Label == 1)
    - Randomly select one row
    - Return the metrics as a dict (including Load_HP, dropping Label)

    Args:
        csv_path: Path to features_multiload.csv.

    Returns:
        A dict containing: RMS, Variance, Kurtosis, Peak_to_Peak, Load_HP.

    Raises:
        FileNotFoundError: If csv_path does not exist.
        ValueError: If required columns are missing or no Fault samples exist.
    """

    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Không tìm thấy file CSV: {csv_path}")

    df = pd.read_csv(csv_path)
    required_cols = set(FEATURE_COLUMNS + ["Load_HP", "Label"])
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"CSV thiếu các cột bắt buộc: {sorted(missing)}")

    df_fault = df[df["Label"] == 1]
    if df_fault.empty:
        raise ValueError("Không có dòng Fault (Label=1) để mô phỏng realtime.")

    row = df_fault.sample(n=1).iloc[0]

    metrics: dict[str, float] = {
        "RMS": float(row["RMS"]),
        "Variance": float(row["Variance"]),
        "Kurtosis": float(row["Kurtosis"]),
        "Peak_to_Peak": float(row["Peak_to_Peak"]),
        "Load_HP": float(row["Load_HP"]),
    }
    return metrics


def generate_maintenance_report(metrics_dict: dict[str, float]) -> str:
    """Generate a Vietnamese maintenance report using Google Gemini.

    The function expects GEMINI_API_KEY to be set in the environment.

    Args:
        metrics_dict: Dictionary containing vibration metrics.

    Returns:
        Generated report text.

    Raises:
        ValueError: If GEMINI_API_KEY is not configured.
    """

    if not os.environ.get("GEMINI_API_KEY"):
        raise ValueError(
            "Thiếu GEMINI_API_KEY. Hãy cấu hình biến môi trường GEMINI_API_KEY (hoặc trong file .env) trước khi chạy."
        )

    client = genai.Client()

    system_instruction = (
        "Bạn là một Chuyên gia Kỹ thuật Bảo trì hệ thống cơ điện tại một nhà máy thông minh. "
        "Nhiệm vụ của bạn là phân tích các thông số rung động bất thường và đưa ra cảnh báo "
        "ngắn gọn, chuyên nghiệp."
    )

    rms = float(metrics_dict["RMS"])
    kurt = float(metrics_dict["Kurtosis"])
    ptp = float(metrics_dict["Peak_to_Peak"])
    load_hp = float(metrics_dict["Load_HP"])

    user_prompt = f"""Bối cảnh vận hành: Động cơ đang hoạt động ở tải {load_hp:.0f} HP.

Dữ liệu đo rung động bất thường (từ hệ thống giám sát):
- RMS: {rms:.6f}
- Kurtosis: {kurt:.6f}
- Peak-to-Peak: {ptp:.6f}

Hãy trả về báo cáo tiếng Việt gồm đúng 3 phần, có tiêu đề rõ ràng:
(1) Đánh giá tình trạng
(2) Nhận định rủi ro vật lý (đặc biệt khi Kurtosis cao)
(3) Đề xuất hành động khẩn cấp

Yêu cầu văn phong: ngắn gọn, chuyên nghiệp, hướng hành động, phù hợp bối cảnh bảo trì công nghiệp.
"""

    prompt = f"""{system_instruction}

{user_prompt}"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
    )
    return response.text


def main() -> None:
    """Route to a load-specific model, score an event, and optionally call Gemini."""

    load_dotenv()

    csv_path = "features_multiload.csv"

    try:
        metrics = simulate_realtime_data(csv_path)
    except (FileNotFoundError, ValueError) as exc:
        print(str(exc))
        return
    except Exception as exc:  # noqa: BLE001
        print(f"Lỗi khi đọc dữ liệu realtime giả lập: {exc}")
        return

    load_hp = metrics.get("Load_HP")
    if load_hp is None:
        print("Thiếu Load_HP trong dữ liệu mô phỏng.")
        return

    model_name = f"iso_forest_load_{int(load_hp)}HP.pkl"
    if not os.path.exists(model_name):
        print(f"Không tìm thấy model file theo tải: {model_name}")
        print(
            "Gợi ý: Hãy chạy pipeline_multimodel.py để tạo các model theo từng mức tải (HP)."
        )
        return

    try:
        model = joblib.load(model_name)
    except Exception as exc:  # noqa: BLE001
        print(f"Không thể load model: {exc}")
        return

    # Self-correction: models in Phase 5 were trained ONLY on FEATURE_COLUMNS.
    # Do NOT pass Load_HP into model.predict().
    sample_df = pd.DataFrame([
        {
            "RMS": float(metrics["RMS"]),
            "Variance": float(metrics["Variance"]),
            "Kurtosis": float(metrics["Kurtosis"]),
            "Peak_to_Peak": float(metrics["Peak_to_Peak"]),
        }
    ])

    try:
        pred = model.predict(sample_df)
    except Exception as exc:  # noqa: BLE001
        print(f"Lỗi khi dự đoán với model: {exc}")
        return

    if int(pred[0]) == -1:
        print("🚨 PHÁT HIỆN BẤT THƯỜNG! Đang kích hoạt AI Agent phân tích...")
        try:
            report = generate_maintenance_report(metrics)
        except ValueError as exc:
            print(str(exc))
            return
        except Exception as exc:  # noqa: BLE001
            print(f"Lỗi khi gọi Gemini API: {exc}")
            return

        print("\n=== BÁO CÁO CHẨN ĐOÁN (Gemini) ===\n")
        print(report)


if __name__ == "__main__":
    main()
